#!/bin/bash

## Uses user profile
if [ -f ~/.bashrc ] ; then . ~/.bashrc ; fi

## Option parsing
fatal_error() {
    echo -e "programmatoid_make error: $1." ;  /bin/rm -rf $target ; exit -1
}
n="false" ; _n=""
target="../public"
while true ; do case "$1" in
    -p ) shift ; target="$1" ; shift ;;
    -c ) shift ; c="$1" ; shift ;;
    -n ) shift ; n="true" ; _n="_neuronoid" ;;
    -i ) shift ; pause=" ; read -p 'Type enter to close' cont" ;;
    -h | -H | --help ) $0 ; exit 0 ;;
    -*) fatal_error "Spurious option '$1'  ($0 -h for help)" ;;
    * ) break ;;
esac ; done
if [ \! -f "$1" ] ; then fatal_error "File not found '`pwd`/$1'." ; fi
if [  "${1##*.}"  \!= "py" -a  "${1##*.}"  \!= "mpl" ] ; then fatal_error "Spurious extension '.${1##*.}'" ; fi

## Usage of the script
if [ -z "$1" ] ; then cat <<EOF 
Usage: $0 [-h | [-c \$c] [-p \$p] [-i] \$prgm.(mpl|py)]
  - The input is either:
     - a programmatoid source in a \$prgm.mpl file, or a
     - a programmatic  source in a \$prgm.py  file,
  - The output is in the o="\$p/\$prgm" directory, with:
      - \$o/prgm.py for the programmatoid translation, if any.
      - \$o/prgm.mw for the programmatoid translation maple trace, if any.
      - \$o/prun.py for the programmatic input or translated source.
      - \$o/*.py for all source dependecies, if any.
      - \$o/prgm.mp4 for the process screen cast.
      - \$o/prgm.wjson (in weak JSON syntax) for the process trace.
      - \$o/prgm.html for the process output presentation.
      - The \$o directory is added to the git repository, if any, when no error.
  Options:
   -p \$p: Target parent publication directory, default is '../public'.
   -c \$c: Optional challenge number.
   -n: Generates a neuronoid implementation (using network weights), default is false.
   -i: Interactively pause at the end of the run (for debug purposes only).
   -h: Shows this usage and exit.
  Note:
    - Space or path separator char in input/output names is not supported.
EOF
exit -1
fi

## Prepares the working and output directory
### Sets the directory name
prgm="${1##*/}" ; prgm="${prgm%.*}" ; if [ -z "${prgm//@/}" ] ; then prgm="$prgm$c$_n" ; else prgm="${prgm//@/$c}$_n" ; fi
target="$target/$prgm"
## Cleans previous files and prepares the repository
/bin/rm -rf $target ; git rm -qrf $target 2> /dev/null ; mkdir -p $target
### Defines the log file name
l="$target/prgm.wjson"
echo -e "{\n programmatoid_make\n prgm: \"$prgm\"\n date: `date '+%Y-%m-%d_%H-%M-%S'`" | tee $l
### Copy the utilities files to run in the target directory
d="`dirname $0`"
cp $d/programmatoid_utils.py $target
if [ \! -z "$c" ] ; then cp $d/../../braincraft/{bot.py,camera.py,environment_$c.py} $target ; fi
prun="$target/prun.py"

# Copies the python program instancing the challenge if any
if [ "${1##*.}" = "py" ] ; then
    sed "s/@/$c/g" < $1 > $prun
    echo -e " source = \"<a href='./prun.py' target='_blank'>$prgm.py</a>\"" | tee -a $l
fi

## Translates programmatoid, if defined in maple
if [ "${1##*.}" = "mpl" ] ; then
   ### Updates the compiler if needed
   make -f - <<EOF
programmatoid_make.mw: programmatoid_make.mpl
	maple -q $^
EOF
   ### Checks maple syntax
   e="`maple -q $1`" ; if [ \! -z "$e" ] ; then fatal_error "Bad maple syntax : \"`echo $e | sed 's/"//g'`\"\n" ; fi
   # Instanciates the challenge if any
   sed "s/challenge *= *0/challenge = $c/g" < $1 | sed "s/neuronoid *= *false/neuronoid = $n/g" > $target/prgm.mpl
   ### Translates the programmatoid equations
   (echo 'read "./programmatoid_make.mw": prgm_compile("'$target'", "'$target/prgm.mpl'");' | maple -q) | sed 's/^"//' | sed 's/  }"/ }/' | grep -v '^$' | tee -a $l 
   ## Creates the file to run
   if [ -f "$target/prgm.py" ]
   then
	 cat <<EOF  > $target/prun.py
# This file is automatically generated, better not edit!
import numpy as np
from bot import Bot
from environment_$c import Environment
from programmatoid_utils import h, H, Id, State, NetworkState, evaluate
from prgm import MyState

if __name__ == "__main__":
	evaluate(Bot, Environment, MyState)
EOF
   else
     fatal_error "The '$target/prgm.py' has not been created, there is a translation error"
   fi
fi

## Runs at the programmatic level
    ### Kills any previous running xterm console with the same geometry
    kill `ps -ef | ps -ef | grep 'xterm.*-geometry 70x11+50+50' | awk '{print $2}'` >/dev/null 2>&1
    ### Starts a pipe for the simplescreenrecorder stdin
    /bin/rm -f  /tmp/prgm-$$-ssr-input ; mkfifo /tmp/prgm-$$-ssr-input
    ### Copies the simplescreenrecorder in /tmp to avoid any change and to set the proper output
    s="`echo $target | sed 's/\//\\\\\//g'`" ; sed < $d/ssr-settings.conf > /tmp/prgm-$$-ssr-settings.conf "s/PRGM/$s/"
    ### Starts a delayed move of the graphic window
    (sleep 1 ; xdotool search --name "Figure 1" windowmove 50 415) &
    ### Starts the simplescreenrecorder using predefined settings in background and piped input
    (sleep 1 ; tail -f /tmp/prgm-$$-ssr-input | simplescreenrecorder --settingsfile=/tmp/prgm-$$-ssr-settings.conf --start-recording --start-hidden >/dev/null 2>&1) &
    ### Starts the program in an xterm console
    xterm -geometry 70x11+50+50 -sb -sl 10000 -rightbar -fa 'Monospace' -fs 18 -title 'programmatic challenge' -e sh -c "python3 $prun 2>&1 | tee -a $l > `tty` $pause "
    ### When done, stops and saves the screen recording and dumps the log file
    (echo  record-pause  ; echo  record-save ) >  /tmp/prgm-$$-ssr-input
    ### Extracts a thumbnail
    sleep 2 ;  ffmpeg -loglevel error -i $target/prgm.mp4 -vframes 10 /tmp/prgm-$$-%d.png ; mv /tmp/prgm-$$-10.png $target/prgm.png
    ### Cleans files
    /bin/rm -f /tmp/prgm-$$*
echo -e "}"  | tee -a $l 

## Finalizes the output file in html
wjson2html="$d/../../etc/wjson-master/src/wjson2html.js"
if [ \! -f "$wjson2html" ] ; then fatal_error "The wjson2html is not installed, are you in the right git branch ?" ; fi
title="${prgm//_/ }"
cat <<EOF >$target/prgm.html
<html>
  <head>
    <title>The $title demonstration</title>
    <meta charset='UTF-8'/> 
  </head>
  <body>
    <h1>The $title demonstration</h1>
     <center><a href="prgm.mp4" target="_blank"><img width="400" src="prgm.png"/></a></center>
     <hr/>
       `$wjson2html < $l`
   </body>
</html>
EOF

## Updates the git repository
git add $target 2> /dev/null
