#!/bin/bash

## Uses user profile
if [ -f ~/.bashrc ] ; then . ~/.bashrc ; fi

## Option parsing
while true ; do case "$1" in
    -c ) shift ; c="$1" ; shift ;;
    -h | -H | --help ) $0 ; exit 0 ;;
    -*) echo "Spurious option '$1'  ($0 -h for help)." ;  $0 ; exit -1 ;;
    * ) break ;;
esac ; done
if [ -f "$1" ] ; then echo "Error: File not found '$1'  ($0 -h for help)." ;  exit -1 ; fi
if [  "${1##*.}"  \!= "py" -o  "${1##*.}"  \!= "mpl" ] ; then echo "Error: Spurious extension '.${1##*.}'  ($0 -h for help)." ;  exit -1 ; fi

## Usage of the script
if [ -z "$1" ] ; then cat <<EOF 
Usage: $0 [-h | [-c \$c] \$prgm.(mpl|py)]
  - The input is:
     - Either a programmatic  source in a \$prgm.py  file,
     - Or a programmatoid source is in a \$prgm.mpl file.
  - The compilation output is saved:
    -  In a out/\$prgm\$c/prgm.py file for the init() and update() procedures.
     - In a out/\$prgm\$c/prgm.mw file for the maple compilation output.
  - The prgm is run executing an automatically generated out/\$prgm\$c/prgm.py file
  - The compilation and execution output is available:
     - In out/\$prgm\$c/prgm.wjson (in weak JSON syntax) in text form.
     - In out/\$prgm\$c/prgm.html in HTML format.
     - In out/\$prgm\$c/prgm.mkv for the screen cast format.
  Options:
   -c \$c : Optional challenge number.
   -h   : shows this usage and exit.
EOF
exit -1
fi

## Prepares the working and output directory
### Sets the directory name
prgm="${1%.*}" ; if [ -z "${prgm//^@/}" ] ; then prgm="$prgm$c" ; else prgm="${$prgm//@/$c}" ; fi
## Cleans previous files and prepares the repository
mkdir -p out/$prgm ; rm -rf out/$prgm/*.*
### Defines uhe log file name
l="out/$prgm/prgm.wjson"
echo -e "{\n programmatoid_mak\n prgm: \"$prgm\"\n date: `date '+%Y-%m-%d_%H-%M-%S'`" | tee $l
### Copy the utilities files to run in the target directory
programmatoid_utils.py out/$prgm
if [ \! -z "$c" ] ; then cp bot.py camera.py environment_$c.py out/$prgm ; fi
prun="out/$prgm/prun.py"

## Translates programmatoid, if defined in maple
if [ "${1##*.}" = "mpl" ] ; then
   ### Updates the compiler if needed
   make -f - <<EOF
programmatoid_make.mw: programmatoid_make.mpl
	maple -q $^
EOF
   ### Checks maple syntax
   e="`maple -q $1`" ; if [ \! -z "$e" ] ; then echo -e "Error: bad maple syntax : \"`echo $e | sed 's/"//g'`\"\n" | tee -a $l ; exit -1 ; fi
  ### Translates the programmatoid equations
  (echo 'read "./programmatoid_make.mw": prgm_compile("'out/$prgm'", "'$1'");' | maple -q) | sed 's/^"//' | sed 's/  }"/ }/' | grep -v '^$' | tee -a $l 
   ## Creates the file to run
  if [ -f "out/$prgm/prgm.py" ]
  then
     if [ -z "$c" ]
     then
	 prun="out/$prgm/prgm.py"
     else
	 cat <<EOF  > out/$prgm/prun.py
# This file is automatically generated, better not edit them
import numpy as np
from bot import Bot
from environment_$c import Environment
from programmatoid_utils import h, H, Id, State, NetworkState, evaluate
from prgm import MyState

if __name__ == "__main__":
	evaluate(Bot, Environment, MyState)
EOF
     fi
  else
      echo -e "Error: the 'out/$prgm/prgm.py' has been created, there is a translation error" | tee -a $l ; exit -1
  fi
else
  # Instanciates the challenge if any
   sed "s/@/$c/g" < $1 > $prun
fi

## Runs at the programmatic level
    ### Kills any previous running xterm console with the same geometry
    kill `ps -ef | ps -ef | grep 'xterm.*-geometry 70x11+50+50' | awk '{print $2}'` >/dev/null 2>&1
    ### Starts a pipe for the simplescreenrecorder stdin
    /bin/rm -f  /tmp/ssr-input ; mkfifo /tmp/ssr-input
    ### Copies the simplescreenrecorder in /tmp to avoid any change and to set the proper output
    sed < ssr-settings.conf > /tmp/ssr-settings.conf "s/PRGM/$prgm/"
    ### Starts a delayed move of the graphic window
    (sleep 1 ; xdotool search --name "Figure 1" windowmove 50 415) &
    ### Starts the simplescreenrecorder using predefined settings in background and piped input
    (sleep 1 ; tail -f /tmp/ssr-input | simplescreenrecorder --settingsfile=/tmp/ssr-settings.conf --start-recording --start-hidden >/dev/null 2>&1) &
    ### Starts the program in an xterm console
    xterm -geometry 70x11+50+50 -sb -sl 10000 -rightbar -fa 'Monospace' -fs 18 -title 'programmatic challenge' -e sh -c "python3 $prun 2>&1 | tee -a $l ; read -p 'Type enter to close' cont "
    ### When done, stops and saves the screen recording and dumps the log file
    (echo  record-pause  ; echo  record-save ) >  /tmp/ssr-input
    cat $l
   
## Finalizes the output file in html
echo -e "}"  | tee -a $l 
if [ -f "../etc/wjson-master/src/wjson2html.js" ]
then
    ../etc/wjson-master/src/wjson2html.js < $l > out/$prgm/prgm.html
else
    echo -e "Installation-error: \"The wjson2html utility is not installed, are you in the right directory of the right branch of the right project ? \""
    (echo "<pre>" ; cat $l ; echo "</pre>") > out/$prgm/prgm.html
fi
