#!/bin/bash

if [ -f ~/.bashrc ] ; then . ~/.bashrc ; fi

## Usage of the script
if [ -z "$1" ] ; then cat <<EOF 
Usage $0 \$prgm
  - The programmatoid source is in a \$prgm.mpl file.
  - The compilation output is saved:
    -  In a \$prgm/prgm.py file for the init() and update() procedures.
     - In a \$prgm/prgm.mw file for the maple compilation output.
  - The test is run executing an automatically generated \$prgm/test.py file
  - The compilation and execution output is available in \$prgm/test.out.wjson (in weak JSON syntax) and \$prgm/test.out.html files 
EOF
exit -1
fi

## The input file name without extension
f="${1%.*}"
## The log file name
l="${f}/test.out.wjson"

## Cleans previous files and starts the log file
rm -rf $f ; mkdir $f
echo -e "{\n\tprogrammatoid_challenge: \"$*\"\n\tdate: `date '+%Y-%m-%d_%H-%M-%S'`" | tee $l

## Runs at the programmatic level
if [ -f "$f.py" ]
then
  python3 $f.py | tee -a $l
else ##Runs at the programmatoid or neuronoid leve;l
    
  ## The environment number 1, 2, or 3
  n="`grep 'challenge *= *[123]' < $f.mpl | sed 's/.*challenge *= *\([123]\).*/\\1/'`"
  if [ -z "$n" ] ; then echo -e "\tfatal-error: \"no 1, 2, or 3 challenge specify in '$f.mpl'\"." | tee -a $l ; exit -1 ; fi

  ## Compiles the programmatoid specifications
  echo -e "\tstart-compiling: true" | tee -a $l 
  ### Updates the compiler if needed
  make -f - <<EOF
programmatoid.mw: programmatoid.mpl
	maple -q $^
EOF
  ### Checks the file syntax
  c="`maple -q $f.mpl`"
  if [ \! -z "$c" ] ; then echo -e "\tfatal-syntax-error : \"`echo $c| sed 's/"//g'`\"\n" | tee -a $l ; exit -1 ; fi
  ### Runs the compilation
  (echo 'read "./programmatoid.mw": prgm_compile("'$f'");' | maple -q) | sed 's/^"//' | sed 's/  }"/\t}/' | grep -v '^$' | tee -a $l 

  ## Builds and executes the given challenge
  if [ -f "$f/prgm.py" ]
  then
     cat <<EOF  > ${f}/test.py
# This file is automatically generated, better not edit them
import numpy as np
from bot import Bot
from environment_$n import Environment
from programmatoid_challenge import sigmoid, step, State, NetworkState, evaluate
from prgm import MyState

if __name__ == "__main__":
	evaluate(Bot, Environment, MyState)
EOF
     echo -e "\tstart-executing: true" | tee -a $l
     cp bot.py camera.py environment_$n.py programmatoid_challenge.py $f
     python3 ${f}/test.py | tee -a $l
  else
     echo -e "\tfatal-compilation-error: \"the '$f.mpl' programmatoid compilation fails, look at '$l'\"" | tee -a $l
  fi
fi

## Finalizes the output file in html
if [ -f "../etc/wjson-master/src/wjson2html.js" ]
then
    echo -e "\treporting-in-html: true" | tee -a $l
    ../etc/wjson-master/src/wjson2html.js < $l > ${f}/test.out.html
    if [ \! -z "$BROWSER" ] ; then
	echo -e "\tshowing-in-browser: true" | tee -a $l ; $BROWSER ${f}/test.out.html
    fi
else
    echo "\tinstallation-error: \"The wjson2html utility is not installed, are you in the right directory of the right branch of the right project ?"
    (cat $l ; echo "}") > ${f}/test.out.html
fi
echo "}"  | tee -a $l 
