#!/bin/bash

if [ -z "$1" ] ; then cat <<EOF 
Usage $0 \$prgm
  - The programmatoid source is in a \$prgm.mpl file.
     - The \$prgm name must have a 1, 2, or 3 digit to define the braincraft task number, thus which environment.
  - The compiled source is in a \$prgm.py file.
     - The compiled log is in a \$prgm.log file.
  - The test is run executing from an automatically generated \$prgm_test_\$d*.py 
     - The execution log is in a \$prgm._test_\$d.log file.
     - The \$d value corresponds to the execution date time.
EOF
exit -1
fi

## The file with extension
f="${1%.*}"

## The environmnet number 1, 2, or 3
n="echo `$1 | sed 's/[^123]*\([123]\).*/\1' | grep '^[123]$'`"
if [ -z "$n" ] ; then echo "No 1, 2, or 3 digit in the '$1' name" ; exit -1 ; fi

# Compiles the programmatoid specifications
echo 'read "./programmatoid.mw": print("'$f' prgm compilation output:", prgm_compile("$f")):' | maple -q |tee $f.log

# Builds and runs the test executable
if [ -f "$f.py" ]
then
   g="$f_test_`date '+%Y-%m-%d_%H-%M-%S'`"
   cat <<EOF  > $g.py
# This file is automatically generated, better not edit them
import numpy as np
from bot import Bot
from environment_$n import Environment
from programmatoid_challenge import evaluate
from $f import init_state, update_state

if __name__ == "__main__":
	evaluate(Bot, Environment, runs = 10, debug = True)
EOF
   (echo "'$f' prgm execution output:" ; python3 $g.py) | tee $g.log
else
    echo "The '$f' programmatoid compilation fails:" ; cat $f.log
fi

