[input]
audio_enabled=false
video_area=fixed
video_frame_rate=30
video_x=50
video_y=50
video_h=910
video_w=1007
video_record_cursor=false
video_scale=false

[output]
add_timestamp=true
container=mkv
container_av=3g2
file=ssr-last-programmatic-run.mkv
separate_files=false
video_allow_frame_skipping=true
video_codec=h264
video_codec_av=alias_pix
video_h264_crf=23
video_h264_preset=1
video_kbit_rate=5000
video_vp8_cpu_used=5

[record]
show_recording_area=true
